# .github/dependabot.yml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    open-pull-requests-limit: 3
    labels:
      - "github_actions"
    schedule:
      interval: "weekly"
      day: friday
      time: '04:00'

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 3
    labels:
      - "docker"
    schedule:
      interval: "weekly"
      day: friday
      time: '04:10'

  # FIXME: https://github.com/dependabot/dependabot-core/issues/11237
  #        dependabot does not know how to parse poetry 2 config files
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   open-pull-requests-limit: 3
  #   labels:
  #     - "pip"
  #   schedule:
  #     interval: "weekly"
  #     day: friday
  #     time: '04:20'
