template: |
  ## What's Changed

  $CHANGES

  ## Full Changelog

  - https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
name-template: "Version $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

categories:
  - title: '🚀 Features'
    labels:
    - 'feature'
    - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🧪 Tests'
    labels:
      - 'test'
  - title: '🏷️ Version Tags'
    labels:
      - 'version'
  - title: '🔖 Release Tags'
    labels:
      - 'release'
  - title: '🧩 Dependencies'
    labels:
      - 'dependencies'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '🚨 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🧹 Code Cleanup'
    labels:
      - 'cleanup'
  - title: '🔧 Config'
    labels:
      - 'config'
  - title: '📦 Packages'
    labels:
      - 'package'
  - title: '🔥 Removals'
    labels:
      - 'removal'
  - title: '🚧 Work In Progress'
    labels:
      - 'wip'
  - title: '🔀 Merges'
    labels:
      - 'merge'
  - title: '🎨 Style'
    labels:
      - 'style'
  - title: '🔊 Logging'
    labels:
      - 'logging'
  - title: '🔇 Silence'
    labels:
      - 'silence'
  - title: '🤖 CI/CD'
    labels:
      - 'ci'

version-resolver:
  major:
    labels:
      - "release-major"
  minor:
    labels:
      - "release-minor"
  patch:
    labels:
      - "release-patch"
  default: patch

autolabeler:
  - label: "release-major"
    title:
      - "/^BREAKING CHANGE:/"
  - label: "release-minor"
    title:
      - "/^feat:/"
      - "/^feat\\(.+\\):/"
